// Generated by scripts/generate-content-map.mjs. Do not edit by hand.
export const storyTranslationMap: Record<string, string> = {
  "/historias/ejemplo-borrador": "/en/stories/sample-draft",
  "/en/stories/sample-draft": "/historias/ejemplo-borrador"
};
