import type { Locale } from "./types";

export const challenges: Record<Locale, string[]> = {
  es: [
    "Elige a alguien. Tienes 15 segundos para convencerle de que las palomas trabajan para el gobierno.",
    "Señala a la persona que sobreviviría más tiempo sin móvil. La mayoría decide.",
    "Durante 20 segundos, habla como si acabaras de ganar un premio por algo completamente inútil.",
    "Elige un objeto cercano y véndelo al grupo como si costara 10.000 euros.",
    "Todos miran al techo. El último en hacerlo debe inventar el nombre de una banda de rock.",
    "Describe tu día usando solamente títulos de películas inventadas.",
    "Elige a alguien y dale un nuevo nombre artístico. No se admiten explicaciones.",
    "Haz una pregunta muy seria sobre un tema completamente absurdo.",
    "Encuentra el objeto más naranja que puedas ver. Tienes 10 segundos.",
    "Imita el sonido que haría una tostadora si tuviera sentimientos.",
    "El grupo tiene 20 segundos para decidir cuál sería el peor nombre para un restaurante elegante.",
    "Señala a alguien. Esa persona debe inventar una excusa para llegar tarde a una boda en Marte.",
    "Di tres cosas que jamás deberían llevar ruedas.",
    "Explica cómo funciona una cuchara como si fueras un científico del año 3026.",
    "Elige una palabra normal y pronúnciala como si fuera una amenaza dramática.",
    "Todos votan: ¿qué objeto de esta habitación tendría más secretos si pudiera hablar?",
    "Inventa un deporte que se pueda jugar sin levantarse de la silla.",
    "Haz el peor eslogan turístico posible para el lugar donde estás.",
    "Elige a alguien. Entre los dos, inventad un saludo secreto en cinco segundos.",
    "Nombra una cosa que mejoraría instantáneamente si fuera amarilla.",
    "Durante 15 segundos, narra lo que está pasando como si fuera un documental de naturaleza.",
    "Inventa una ley absurda que sólo sea válida los martes.",
    "Señala el objeto que peor quedaría como sombrero. Defiende tu elección.",
    "Di el nombre de un superhéroe cuyo único poder sea encontrar aparcamiento.",
    "Todos eligen una pose. La última persona en quedarse quieta pierde esta ronda imaginaria.",
    "Convierte el nombre de alguien del grupo en el título de una telenovela.",
  ],
  en: [
    "Pick someone. You have 15 seconds to convince them that pigeons work for the government.",
    "Point at the person who would survive longest without a phone. Majority wins.",
    "For 20 seconds, speak as if you have just won an award for something completely useless.",
    "Pick a nearby object and sell it to the group as if it cost £10,000.",
    "Everyone look at the ceiling. The last person to do it must invent a rock band name.",
    "Describe your day using only made-up film titles.",
    "Pick someone and give them a new stage name. No explanations allowed.",
    "Ask a very serious question about a completely ridiculous subject.",
    "Find the most orange thing you can see. You have 10 seconds.",
    "Imitate the sound a toaster would make if it had feelings.",
    "The group has 20 seconds to decide the worst possible name for a fancy restaurant.",
    "Point at someone. They must invent an excuse for arriving late to a wedding on Mars.",
    "Name three things that should never have wheels.",
    "Explain how a spoon works as if you were a scientist from the year 3026.",
    "Choose an ordinary word and say it as if it were a dramatic threat.",
    "Everyone votes: which object in the room would have the most secrets if it could talk?",
    "Invent a sport that can be played without leaving your chair.",
    "Create the worst possible tourism slogan for wherever you are.",
    "Pick someone. Together, invent a secret greeting in five seconds.",
    "Name one thing that would instantly improve if it were yellow.",
    "For 15 seconds, narrate what is happening like a wildlife documentary.",
    "Invent a ridiculous law that only applies on Tuesdays.",
    "Point at the object that would make the worst hat. Defend your choice.",
    "Name a superhero whose only power is finding a parking space.",
    "Everyone strikes a pose. The last person to freeze loses this imaginary round.",
    "Turn someone's name into the title of a soap opera.",
  ],
};

export type ChoiceKind = "truth" | "dare" | "bad";

export const choicePrompts: Record<Locale, Record<ChoiceKind, string[]>> = {
  es: {
    truth: [
      "¿Qué cosa completamente normal te parece sospechosamente sobrevalorada?",
      "¿Qué pequeño lujo defenderías ante un tribunal?",
      "¿Qué palabra te cae mal sin una buena razón?",
      "¿Cuál es tu talento más inútil?",
      "¿Qué comida fingirías entender en un restaurante demasiado elegante?",
      "¿Qué moda del pasado no debería volver jamás?",
      "¿Qué objeto cotidiano tendría la peor personalidad?",
      "¿Qué trabajo harías fatal incluso con un mes de entrenamiento?",
    ],
    dare: [
      "Haz una reverencia solemne a la persona más cercana.",
      "Presenta tu vaso, taza o botella como si fuera una celebridad internacional.",
      "Di tu nombre como si anunciaras el combate del siglo.",
      "Camina tres pasos como si el suelo fuera una alfombra roja.",
      "Inventa y demuestra un saludo oficial para los domingos.",
      "Haz un anuncio de cinco segundos para una piedra imaginaria.",
      "Pon cara de absoluta sorpresa durante diez segundos sin explicar por qué.",
      "Convierte la próxima frase que digas en una profecía dramática.",
    ],
    bad: [
      "Propón un nombre terrible para una aplicación que nadie necesita.",
      "Diseña mentalmente un paraguas para peces. Explícalo en una frase.",
      "Inventa el peor sabor de helado posible que siga siendo técnicamente comida.",
      "Elige un animal para dirigir una reunión de empresa. Justifica el nombramiento.",
      "Crea un lema motivacional que no motive a nadie.",
      "Inventa un servicio premium completamente innecesario.",
      "Propón una función nueva y absurda para una puerta.",
      "Da un consejo pésimo para empezar bien un lunes, pero que sea inofensivo.",
    ],
  },
  en: {
    truth: [
      "What completely normal thing do you think is suspiciously overrated?",
      "What tiny luxury would you defend in court?",
      "Which word annoys you for no good reason?",
      "What is your most useless talent?",
      "What food would you pretend to understand in an overly fancy restaurant?",
      "Which trend from the past should never come back?",
      "Which everyday object would have the worst personality?",
      "What job would you be terrible at even after a month of training?",
    ],
    dare: [
      "Give the nearest person a solemn bow.",
      "Introduce your glass, mug or bottle as if it were an international celebrity.",
      "Say your name as if you were announcing the fight of the century.",
      "Walk three steps as if the floor were a red carpet.",
      "Invent and demonstrate an official greeting for Sundays.",
      "Make a five-second advert for an imaginary stone.",
      "Look completely astonished for ten seconds and refuse to explain why.",
      "Turn the next sentence you say into a dramatic prophecy.",
    ],
    bad: [
      "Suggest a terrible name for an app nobody needs.",
      "Mentally design an umbrella for fish. Explain it in one sentence.",
      "Invent the worst ice-cream flavour that is still technically food.",
      "Choose an animal to chair a business meeting. Defend the appointment.",
      "Create a motivational slogan that motivates nobody.",
      "Invent a completely unnecessary premium service.",
      "Suggest a new and ridiculous feature for a door.",
      "Give terrible but harmless advice for starting a Monday well.",
    ],
  },
};
